include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build uenv:
  extends: ['.f7t-runner', '.f7t-uenv-builder']
  stage: build
  variables:
    UENV_RECIPE: recipe
    UENV_SYSTEM: $system
    UENV_TAG: $CI_PIPELINE_ID
    UENV_NAME: $name
    UENV_VERSION: $version
    UENV_UARCH: $uarch
    UENV_REPO_DIR: $CSCS_REGISTRY/uenv/service/$system/$uarch
    F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
    UENV_LOCAL: 'NO'
    SLURM_TIMELIMIT: '04:00:00'
  rules:
    - if: $system == "daint"
      variables:
        F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
        FIRECREST_SYSTEM: daint
        ARCH: 'aarch64'
    - if: $system == "santis"
      variables:
        F7T_URL: "https://api.cscs.ch/cw/firecrest/v1"
        FIRECREST_SYSTEM: santis
        ARCH: 'aarch64'
    - if: $system == "clariden"
      variables:
        F7T_URL: "https://api.cscs.ch/ml/firecrest/v1"
        FIRECREST_SYSTEM: clariden
        SLURM_ACCOUNT: 'a-djenkssl'
        ARCH: 'aarch64'
    - if: $system == "bristen"
      variables:
        F7T_URL: "https://api.cscs.ch/ml/firecrest/v1"
        FIRECREST_SYSTEM: bristen
        SLURM_ACCOUNT: 'a-djenkssl'
        ARCH: 'x86_64'
    - if: $system == "eiger"
      variables:
        F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
        FIRECREST_SYSTEM: eiger
        SLURM_CONSTRAINT: mc
        ARCH: 'x86_64'
    - if: $system == "balfrin"
      variables:
        F7T_URL: 'https://api.cscs.ch/mch/firecrest/v1'
        FIRECREST_SYSTEM: balfrin
        ARCH: 'x86_64'
    - if: $system == "beverin" && $uarch == "mi200"
      variables:
        F7T_URL: "https://api.tds.cscs.ch/stp/firecrest/v2"
        F7T_TOKEN_URL: "https://auth-tds.cscs.ch/auth/realms/firecrest-clients/protocol/openid-connect/token"
        F7T_CLIENT_ID: $F7T_TDS_CLIENT_ID
        F7T_CLIENT_SECRET: $F7T_TDS_CLIENT_SECRET
        FIRECREST_SYSTEM: beverin
        SLURM_PARTITION: mi200
        ARCH: 'x86_64'
    - if: $system == "beverin" && $uarch == "mi300"
      variables:
        F7T_URL: "https://api.tds.cscs.ch/stp/firecrest/v2"
        F7T_TOKEN_URL: "https://auth-tds.cscs.ch/auth/realms/firecrest-clients/protocol/openid-connect/token"
        F7T_CLIENT_ID: $F7T_TDS_CLIENT_ID
        F7T_CLIENT_SECRET: $F7T_TDS_CLIENT_SECRET
        FIRECREST_SYSTEM: beverin
        SLURM_PARTITION: mi300
        ARCH: 'x86_64'
    # make sure a job is always added, then maybe the job output will give a better description why it failed
    - when: always
