include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build uenv:
  extends: ['.f7t-runner', '.f7t-uenv-builder']
  stage: build
  variables:
    UENV_RECIPE: recipe
    UENV_SYSTEM: $system
    UENV_TAG: $CI_PIPELINE_ID
    UENV_NAME: $name
    UENV_VERSION: $version
    UENV_UARCH: $uarch
    UENV_REPO_DIR: $CSCS_REGISTRY/uenv/service/$system/$uarch
    F7T_URL: 'https://invalid-url'
    UENV_LOCAL: 'NO'
    SLURM_TIMELIMIT: '04:00:00'
  rules:
    - if: $system == "daint"
      variables:
        F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
        FIRECREST_SYSTEM: daint
        ARCH: 'aarch64'
    - if: $system == "todi"
      variables:
        F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
        FIRECREST_SYSTEM: todi
        ARCH: 'aarch64'
    - if: $system == "eiger"
      variables:
        F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
        FIRECREST_SYSTEM: eiger
        SLURM_CONSTRAINT: mc
        ARCH: 'x86_64'
    - if: $system == "balfrin"
      variables:
        F7T_URL: 'https://api.cscs.ch/mch/firecrest/v1'
        FIRECREST_SYSTEM: balfrin
        ARCH: 'x86_64'
