include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - build

build uenv:
  extends: ['.f7t-runner', '.uenv-builder']
  tags: [f7t-runner-tds] # TODO: remove this tag, that should not run on the TDS runner
  stage: build
  variables:
    STACK_RECIPE: recipe
    STACK_SYSTEM: $system
    STACK_NAME: $CSCS_REGISTRY_PATH/public/$CI_PIPELINE_ID/$name/$version:latest
    F7T_URL: 'https://invalid-url'
    SLURM_TIMEOUT: '04:00:00'
    rules:
      - if: $STACK_SYSTEM == "daint"
        variables:
          F7T_URL: "https://api.cscs.ch/hpc/firecrest/v1"
          ARCH: 'aarch64'
      - if: $STACK_SYSTEM == "todi"
        variables:
          F7T_URL: "https://api.cscs.ch/cscs/firecrest/v1"
          ARCH: 'aarch64'
      - if: $STACK_SYSTEM == "eiger"
        variables:
          F7T_URL: 'https://firecrest.cscs.ch'
          SLURM_CONSTRAINT: mc
          ARCH: 'x86_64'
      - if: $STACK_SYSTEM == "balfrin"
        variables:
          F7T_URL: 'https://api.cscs.ch/mch/firecrest/v1'
          ARCH: 'x86_64'
